name: Deploy to magic branch

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to build-branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.x.x
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'pnpm'    
      - name: Install dependencies
        run: pnpm install --prefer-offline --no-lockfile
        env:
          CI: true
      - name: Build dist
        run: yarn build
      - name: Cleanup folder structure
        run: rm -rf prettier.config.js tsconfig.eslint.json tsconfig.base.json tsconfig.json yarn.lock .prettierignore .gitignore .github .editorconfig .eslintignore .stylelintrc .vscode .eslintrc
      - name: Run deploy script
        run: |
          git config user.name "github-actions[bot]" && git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          pnpm run deploy