name: Linting

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint and Typecheck, Node
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.x.x
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'pnpm'    
      - name: Install dependencies
        run: pnpm install --prefer-offline --frozen-lockfile
        env:
          CI: true
      - run: pnpm -C package lint
        env:
          CI: true
        timeout-minutes: 20
